### ISSUE TITLE
custom op roi_pooling.so error with tf 1.4

### ISSUE THREAD

**Issue by learnbott** [xdever/RFCN-tensorflow#20]
When running the code (thank you!) the tf.load_op_library in ROIPoolingWrapper.py yields the error, "roi_pooling.so: undefined symbol: _ZTIN10tensorflow8OpKernelE". 

It loads in tf 1.3 but other issues exist (that are fixed in tf 1.4 exist) that don't allow the code to run.

**Comment by learnbott** [comment]
fixed it with this issue: https://github.com/tensorflow/tensorflow/issues/13607

**Comment by Kongsea** [comment]
@learnbott Could you give a detailed explaination?
I have encountered the same error as you and tried to solve it using the method you mentioned. However, the error still exists.
Please do me a favor, thank you.
